let courses = [

    //fisk-----------------------------------------------------
    {
        course: "Fiskeboller i hvit saus med potet og gulrøtter",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 2,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false,
        type: "fish"
    },
    {
        course: "Sashimisalat med mango, vårløk og koriander",
        area: "Japan",
        category: "Sushi",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 2,
        friday: true,
        sunday: true,
        glutenFree: true,
        lactoseFree: true,
        type: "fish"
    },
    {
        course: "Fiskepinner og potetterninger med råkostsalat",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 2,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: true,
        type: "fish"
    },
    {
        course: "Pokebowl",
        area: "Japan",
        category: "Sushi",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 2,
        price: 3,
        friday: true,
        sunday: true,
        glutenFree: true,
        lactoseFree: true,
        type: "fish"
    },
    {
        course: "Fiskegrateng med potet og grønnsaksblanding",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 3,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "fish"
    },
    {
        course: "Panert torsk med potetmos og råkostsalat",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "fish"
    },
    {
        course: "Tandoorilaks med ris, yoghurt og mango",
        area: "India",
        category: "Ris",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "fish"
    },
    {
        course: "Laks med pesto, grønnsaker og pasta",
        area: "Norge",
        category: "Pasta",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: true,
        type: "fish"
    },
    {
        course: "Laks med pasta og aspargesbønner",
        area: "Norge",
        category: "Pasta",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false,
        type: "fish"
    },
    {
        course: "Fiskekaker, potet og gulrot",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 2,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "fish"
    },
    {
        course: "Fiskeburger med salat",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "fish"
    },
    {
        course: "Laks med crème fraiche og soyasaus med potet og gulrot",
        area: "Norge",
        category: "Tallerken",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 2,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false,
        type: "fish"
    },
    {
        course: "Rød karri thai fiskesuppe",
        area: "Thailand",
        category: "Suppe",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 3,
        price: 3,
        friday: false,
        sunday: true,
        glutenFree: true,
        lactoseFree: false,
        type: "fish"
    },
    {
        course: "Bulgursalat med mango, avokado og røkelaks",
        area: "Midtøsten",
        category: "Salat",
        vegetarian: false,
        fish: true,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: true,
        type: "fish"
    },
  



    //Kjøtt-------------------------------------------------------------
    {
        course: "Kjøttkaker i brun saus med kålstuing",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 2,
        price: 2,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Pølser med rotmos og erter",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 2,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Kyllingshawarma med pitabrød",
        area: "Norge",
        category: "Tallerken",
        vegetarian: false,
        fish: false,
        whiteMeat: true,
        redMeat: false,
        time: 3,
        price: 2,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Kyllingsalat med pasta",
        area: "",
        category: "Salat",
        vegetarian: false,
        fish: false,
        whiteMeat: true,
        redMeat: false,
        time: 2,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: true,
        type: "meat"
    },
    {
        course: "Kjøttboller med potetmos, grønnsaksblanding og tyttebærsyltetøy",
        area: "Sverige",
        category: "Tradisjon",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 1,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Pasta Bolognaise",
        area: "Italia",
        category: "Pasta",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 2,
        price: 1,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: true,
        type: "meat"
    },
    {
        course: "Pasta Carbonara",
        area: "Italia",
        category: "Pasta",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Omelett med ost og skinke",
        area: "Norge",
        category: "Egg",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Taco",
        area: "Mexico",
        category: "Texmex",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 2,
        price: 2,
        friday: true,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Pasta med kjøttboller i tomatsaus",
        area: "Italia",
        category: "Pasta",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 2,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Kylling tikka masala",
        area: "India",
        category: "Gryterett",
        vegetarian: false,
        fish: false,
        whiteMeat: true,
        redMeat: false,
        time: 3,
        price: 2,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Pad thai med kylling",
        area: "Thailand",
        category: "Gryterett",
        vegetarian: false,
        fish: false,
        whiteMeat: true,
        redMeat: false,
        time: 2,
        price: 3,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Minestronesuppe med kylling",
        area: "Italia",
        category: "Suppe",
        vegetarian: false,
        fish: false,
        whiteMeat: true,
        redMeat: false,
        time: 3,
        price: 2,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: true,
        type: "meat"
    },
    {
        course: "Kylling Satay med ris og mango",
        area: "Øst-Asia",
        category: "Tallerken",
        vegetarian: false,
        fish: false,
        whiteMeat: true,
        redMeat: false,
        time: 3,
        price: 3,
        friday: true,
        sunday: true,
        glutenFree: false,
        lactoseFree: true,
        type: "meat"
    },
    {
        course: "Lasagne med salat",
        area: "Italia",
        category: "Pasta",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 3,
        price: 2,
        friday: true,
        sunday: true,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Pølse- og pastagrateng med blomkål og brokkoli",
        area: "Norge",
        category: "Grateng",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 3,
        price: 2,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Makaronigrateng med skinke",
        area: "Norge",
        category: "Grateng",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 3,
        price: 2,
        friday: true,
        sunday: true,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Quesedilla med kylling og salat",
        area: "Norge",
        category: "Texmex",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 3,
        price: 3,
        friday: true,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Pitapizza med ost, skinke og salat",
        area: "Norge",
        category: "Pizza",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Chilli con carne",
        area: "Mexico",
        category: "Gryterett",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 3,
        price: 2,
        friday: false,
        sunday: true,
        glutenFree: true,
        lactoseFree: true,
        type: "meat"
    },
    {
        course: "Kyllingkjøttboller og pasta med tomatsaus, ruccola og parmesan",
        area: "Italia",
        category: "Pasta",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 2,
        price: 2,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Wok med nudler og svinekjøtt",
        area: "Italia",
        category: "Wok",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 3,
        price: 2,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: true,
        type: "meat"
    },
    {
        course: "Pasta penne med rød pesto, blomkål og chorizo",
        area: "Italia",
        category: "Pasta",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 2,
        price: 2,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: true,
        type: "meat"
    },
    {
        course: "Fredagspizza",
        area: "Italia",
        category: "Pizza",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 2,
        price: 2,
        friday: true,
        sunday: false,
        glutenFree: false,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Lapskaus",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 1,
        price: 1,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: true,
        type: "meat"
    },
    {
        course: "Koteletter med surkål, gulrøtter og poteter",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 2,
        price: 1,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: true,
        type: "meat"
    },
    {
        course: "Viltgryte",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 3,
        price: 3,
        friday: false,
        sunday: true,
        glutenFree: true,
        lactoseFree: false,
        type: "meat"
    },
    {
        course: "Kyllingform med spinat, paprika og parmesan",
        area: "Norge",
        category: "Grateng",
        vegetarian: false,
        fish: false,
        whiteMeat: false,
        redMeat: true,
        time: 3,
        price: 3,
        friday: true,
        sunday: true,
        glutenFree: true,
        lactoseFree: false,
        type: "meat"
    },

    //Vegetar---------------------------------------------------------------
    {
        course: "Chilli sin carne med svarte bønner",
        area: "Mexico",
        category: "Gryterett",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 3,
        price: 1,
        friday: false,
        sunday: true,
        glutenFree: true,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Fredagspizza vegetar",
        area: "Italia",
        category: "Pizza",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 2,
        price: 1,
        friday: true,
        sunday: false,
        glutenFree: false,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Pai med soltørket tomat, feta og spinat",
        area: "",
        category: "Pizza",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 2,
        price: 2,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Blomkålsuppe",
        area: "Norge",
        category: "Suppe",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Soppsuppe",
        area: "Norge",
        category: "Suppe",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Spinatsuppe med ingefær, kokosmelk og egg",
        area: "Thailand",
        category: "Suppe",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false, 
        type: "veg"
    },
  
    {
        course: "Grønnsaksuppe",
        area: "Norge",
        category: "Suppe",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: true, 
        type: "veg"
    },
    {
        course: "Vegetarlasagne med røde linser og salat",
        area: "Italia",
        category: "Pasta",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 3,
        price: 1,
        friday: true,
        sunday: true,
        glutenFree: false,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Risengrynsgrøt",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 2,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Sopprisotto",
        area: "Italia",
        category: "Ris",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 3,
        price: 1,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Brokkoli og blomkålsuppe",
        area: "Norge",
        category: "Suppe",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Linsesuppe",
        area: "India",
        category: "Suppe",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Tomatsuppe med egg og makaroni",
        area: "Norge",
        category: "Suppe",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 1,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: false,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Gulrotsuppe",
        area: "Norge",
        category: "Suppe",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 2,
        price: 1,
        friday: false,
        sunday: false,
        glutenFree: true,
        lactoseFree: true, 
        type: "veg"
    },
    {
        course: "Kikertgryte med kokosmelk og røde linser",
        area: "Øst-Asia",
        category: "Gryterett",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 3,
        price: 1,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: false, 
        type: "veg"
    },
    {
        course: "Pannekaker",
        area: "Norge",
        category: "Tradisjon",
        vegetarian: true,
        fish: false,
        whiteMeat: false,
        redMeat: false,
        time: 3,
        price: 1,
        friday: false,
        sunday: true,
        glutenFree: false,
        lactoseFree: false, 
        type: "veg"
    },
  

    
]

const days = [
    {day: 'Mandag', type: "hverdag"}, 
    {day: 'Tirsdag', type: "hverdag"}, 
    {day: 'Onsdag', type: "hverdag"}, 
    {day: 'Torsdag', type: "hverdag"}, 
    {day: 'Fredag', type: "fredag"},
    {day: 'Lørdag', type: "hverdag"},
    {day: 'Søndag', type: "søndag"},
    ];
