let middager = [

    //fisk-----------------------------------------------------
    {
        navn: "Fiskeboller i hvit saus med potet og gulrøtter",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 2,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false,
        type: "fisk"
    },
    {
        navn: "Sashimisalat med mango, vårløk og koriander",
        område: "Japan",
        kategori: "Sushi",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 2,
        fredag: true,
        søndag: true,
        glutenfri: true,
        laktosefri: true,
        type: "fisk"
    },
    {
        navn: "Fiskepinner og potetterninger med råkostsalat",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 2,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: true,
        type: "fisk"
    },
    {
        navn: "Pokebowl",
        område: "Japan",
        kategori: "Sushi",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 2,
        pris: 3,
        fredag: true,
        søndag: true,
        glutenfri: true,
        laktosefri: true,
        type: "fisk"
    },
    {
        navn: "Fiskegrateng med potet og grønnsaksblanding",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 3,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "fisk"
    },
    {
        navn: "Panert torsk med potetmos og råkostsalat",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "fisk"
    },
    {
        navn: "Tandoorilaks med ris, yoghurt og mango",
        område: "India",
        kategori: "Ris",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "fisk"
    },
    {
        navn: "Laks med pesto, grønnsaker og pasta",
        område: "Norge",
        kategori: "Pasta",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: true,
        type: "fisk"
    },
    {
        navn: "Laks med pasta og aspargesbønner",
        område: "Norge",
        kategori: "Pasta",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false,
        type: "fisk"
    },
    {
        navn: "Fiskekaker, potet og gulrot",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 2,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "fisk"
    },
    {
        navn: "Fiskeburger med salat",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "fisk"
    },
    {
        navn: "Laks med crème fraiche og soyasaus med potet og gulrot",
        område: "Norge",
        kategori: "Tallerken",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 2,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false,
        type: "fisk"
    },
    {
        navn: "Rød karri thai fiskesuppe",
        område: "Thailand",
        kategori: "Suppe",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 3,
        pris: 3,
        fredag: false,
        søndag: true,
        glutenfri: true,
        laktosefri: false,
        type: "fisk"
    },
    {
        navn: "Bulgursalat med mango, avokado og røkelaks",
        område: "Midtøsten",
        kategori: "Salat",
        vegetar: false,
        fisk: true,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: true,
        type: "fisk"
    },
  



    //Kjøtt-------------------------------------------------------------
    {
        navn: "Kjøttkaker i brun saus med kålstuing",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 2,
        pris: 2,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Pølser med rotmos og erter",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 2,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Kyllingshawarma med pitabrød",
        område: "Norge",
        kategori: "Tallerken",
        vegetar: false,
        fisk: false,
        kjøttHvitt: true,
        kjottRodt: false,
        tid: 3,
        pris: 2,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Kyllingsalat med pasta",
        område: "",
        kategori: "Salat",
        vegetar: false,
        fisk: false,
        kjøttHvitt: true,
        kjottRodt: false,
        tid: 2,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: true,
        type: "kjott"
    },
    {
        navn: "Kjøttboller med potetmos, grønnsaksblanding og tyttebærsyltetøy",
        område: "Sverige",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 1,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Pasta Bolognaise",
        område: "Italia",
        kategori: "Pasta",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 2,
        pris: 1,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: true,
        type: "kjott"
    },
    {
        navn: "Pasta Carbonara",
        område: "Italia",
        kategori: "Pasta",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Omelett med ost og skinke",
        område: "Norge",
        kategori: "Egg",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Taco",
        område: "Mexico",
        kategori: "Texmex",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 2,
        pris: 2,
        fredag: true,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Pasta med kjøttboller i tomatsaus",
        område: "Italia",
        kategori: "Pasta",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 2,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Kylling tikka masala",
        område: "India",
        kategori: "Gryterett",
        vegetar: false,
        fisk: false,
        kjøttHvitt: true,
        kjottRodt: false,
        tid: 3,
        pris: 2,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Pad thai med kylling",
        område: "Thailand",
        kategori: "Gryterett",
        vegetar: false,
        fisk: false,
        kjøttHvitt: true,
        kjottRodt: false,
        tid: 2,
        pris: 3,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Minestronesuppe med kylling",
        område: "Italia",
        kategori: "Suppe",
        vegetar: false,
        fisk: false,
        kjøttHvitt: true,
        kjottRodt: false,
        tid: 3,
        pris: 2,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: true,
        type: "kjott"
    },
    {
        navn: "Kylling Satay med ris og mango",
        område: "Øst-Asia",
        kategori: "Tallerken",
        vegetar: false,
        fisk: false,
        kjøttHvitt: true,
        kjottRodt: false,
        tid: 3,
        pris: 3,
        fredag: true,
        søndag: true,
        glutenfri: false,
        laktosefri: true,
        type: "kjott"
    },
    {
        navn: "Lasagne med salat",
        område: "Italia",
        kategori: "Pasta",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 3,
        pris: 2,
        fredag: true,
        søndag: true,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Pølse- og pastagrateng med blomkål og brokkoli",
        område: "Norge",
        kategori: "Grateng",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 3,
        pris: 2,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Makaronigrateng med skinke",
        område: "Norge",
        kategori: "Grateng",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 3,
        pris: 2,
        fredag: true,
        søndag: true,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Quesedilla med kylling og salat",
        område: "Norge",
        kategori: "Texmex",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 3,
        pris: 3,
        fredag: true,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Pitapizza med ost, skinke og salat",
        område: "Norge",
        kategori: "Pizza",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Chilli con carne",
        område: "Mexico",
        kategori: "Gryterett",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 3,
        pris: 2,
        fredag: false,
        søndag: true,
        glutenfri: true,
        laktosefri: true,
        type: "kjott"
    },
    {
        navn: "Kyllingkjøttboller og pasta med tomatsaus, ruccola og parmesan",
        område: "Italia",
        kategori: "Pasta",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 2,
        pris: 2,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Wok med nudler og svinekjøtt",
        område: "Italia",
        kategori: "Wok",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 3,
        pris: 2,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: true,
        type: "kjott"
    },
    {
        navn: "Pasta penne med rød pesto, blomkål og chorizo",
        område: "Italia",
        kategori: "Pasta",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 2,
        pris: 2,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: true,
        type: "kjott"
    },
    {
        navn: "Fredagspizza",
        område: "Italia",
        kategori: "Pizza",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 2,
        pris: 2,
        fredag: true,
        søndag: false,
        glutenfri: false,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Lapskaus",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: true,
        type: "kjott"
    },
    {
        navn: "Koteletter med surkål, gulrøtter og poteter",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 2,
        pris: 1,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: true,
        type: "kjott"
    },
    {
        navn: "Viltgryte",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 3,
        pris: 3,
        fredag: false,
        søndag: true,
        glutenfri: true,
        laktosefri: false,
        type: "kjott"
    },
    {
        navn: "Kyllingform med spinat, paprika og parmesan",
        område: "Norge",
        kategori: "Grateng",
        vegetar: false,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: true,
        tid: 3,
        pris: 3,
        fredag: true,
        søndag: true,
        glutenfri: true,
        laktosefri: false,
        type: "kjott"
    },

    //Vegetar---------------------------------------------------------------
    {
        navn: "Chilli sin carne med svarte bønner",
        område: "Mexico",
        kategori: "Gryterett",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 3,
        pris: 1,
        fredag: false,
        søndag: true,
        glutenfri: true,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Fredagspizza vegetar",
        område: "Italia",
        kategori: "Pizza",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 2,
        pris: 1,
        fredag: true,
        søndag: false,
        glutenfri: false,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Pai med soltørket tomat, feta og spinat",
        område: "",
        kategori: "Pizza",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 2,
        pris: 2,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Blomkålsuppe",
        område: "Norge",
        kategori: "Suppe",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Soppsuppe",
        område: "Norge",
        kategori: "Suppe",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Spinatsuppe med ingefær, kokosmelk og egg",
        område: "Thailand",
        kategori: "Suppe",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false, 
        type: "vegetar"
    },
  
    {
        navn: "Grønnsaksuppe",
        område: "Norge",
        kategori: "Suppe",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: true, 
        type: "vegetar"
    },
    {
        navn: "Vegetarlasagne med røde linser og salat",
        område: "Italia",
        kategori: "Pasta",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 3,
        pris: 1,
        fredag: true,
        søndag: true,
        glutenfri: false,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Risengrynsgrøt",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 2,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Sopprisotto",
        område: "Italia",
        kategori: "Ris",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 3,
        pris: 1,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Brokkoli og blomkålsuppe",
        område: "Norge",
        kategori: "Suppe",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Linsesuppe",
        område: "India",
        kategori: "Suppe",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Tomatsuppe med egg og makaroni",
        område: "Norge",
        kategori: "Suppe",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 1,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: false,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Gulrotsuppe",
        område: "Norge",
        kategori: "Suppe",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 2,
        pris: 1,
        fredag: false,
        søndag: false,
        glutenfri: true,
        laktosefri: true, 
        type: "vegetar"
    },
    {
        navn: "Kikertgryte med kokosmelk og røde linser",
        område: "Øst-Asia",
        kategori: "Gryterett",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 3,
        pris: 1,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: false, 
        type: "vegetar"
    },
    {
        navn: "Pannekaker",
        område: "Norge",
        kategori: "Tradisjon",
        vegetar: true,
        fisk: false,
        kjøttHvitt: false,
        kjottRodt: false,
        tid: 3,
        pris: 1,
        fredag: false,
        søndag: true,
        glutenfri: false,
        laktosefri: false, 
        type: "vegetar"
    },
  

    
]

const dager = [
    {dag: 'Mandag', type: "hverdag"}, 
    {dag: 'Tirsdag', type: "hverdag"}, 
    {dag: 'Onsdag', type: "hverdag"}, 
    {dag: 'Torsdag', type: "hverdag"}, 
    {dag: 'Fredag', type: "fredag"},
    {dag: 'Lørdag', type: "hverdag"},
    {dag: 'Søndag', type: "søndag"},
    ];

//IDEER: sondagsmiddagfunksjon - marker sondagsmiddag på søndager